name: MoneyLevel
api: ["3.6"]
main: mydeacy\moneylevel\MoneyLevel
version: RE-CREATE2.0.1
author: MyDeacy
loadBefore: ["EconomyAPI"]
depend: ["EconomyAPI"]
load: STARTUP
description: "Economy level plugin"
commands:
  lvup:
    description: "レベルを上げる"
    usage: "/lvup {amount}"
    permission: moneylevel.lvup
  seelv:
    description: "レベル見る"
    usage: "/seelv {target}"
    permission: moneylevel.viewlv
  toplv:
    description: "レベルランキング"
    usage: "/toplv {page}"
    permission: moneylevel.toplv
  lvhelp:
    description: "MoneyLevel's help"
    usage: "/lvhelp"
    permission: moneylevel.lvhelp
  setlv:
    description: "レベルセット"
    usage: "/setlv {target} {amount}"
    permission: moneylevel.setlv

permissions:
  moneylevel.*:
    default: op
    children:
      moneylevel.lvup:
        default: false
      moneylevel.viewlv:
        default: true
      moneylevel.toplv:
        default: true
      moneylevel.lvhelp:
        default: false
